name: Build and Deploy to GitHub Pages (via /docs)

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Regenerate static site in /docs
        run: python generate.py

      - name: Auto commit updated site
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[bot] regenerate GitHub Pages content"
          branch: main
          file_pattern: docs/*
